simpleArgs: &simple-args
  initialMoney: 10000
  moneyToTransfer: 10
  numberOfAccounts: &number-of-accounts 200

test:
  name: simple
  description: >-
    Test for Reordering Algorithm...
  workers:
    number: 1
  rounds:
    - label: open
      description: >-
        Test description for the opening of an account through the deployed contract.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 256
      workload:
        module: benchmarks/scenario/simple/open.js
        arguments: *simple-args
    - label: query
      description: Test description for the query performance of the deployed contract.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 256
      workload:
        module: benchmarks/scenario/simple/query.js
        arguments: *simple-args
    - label: test
      description: Test description for R2w2 between accounts.
      txNumber: 5000
      rateControl:
        type: fixed-rate
        opts:
          tps: 256
      workload:
        module: benchmarks/scenario/simple/test.js
        arguments:
          << : *simple-args
