simpleArgs: &simple-args
  initialMoney: 10000
  moneyToTransfer: 10
  numberOfAccounts: &number-of-accounts 2

test:
  name: simple
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.
  workers:
    number: 1
  rounds:
    - label: copy
      description: Test description for copying money between accounts.
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: benchmarks/scenario/simple/copy.js
        arguments:
          << : *simple-args
